### ISSUE TITLE
Backport request

### ISSUE THREAD

**Issue by CocolinoFan** [hamarituc/gentoo-overlay#7]
Hello o/

There was an [issue](https://github.com/f4exb/sdrangel/issues/1997) building [sdrangel-7.18.1](https://gpo.zugaina.org/net-wireless/sdrangel). 
I think it was fixed. 
[From what I understand](https://forums.gentoo.org/viewtopic-t-1167549.html), now the fix need to be backported.

Thank you for maintaining this overlay o7

**Comment by hamarituc** [comment]
Thanks for using my overlay. I think updating `dev-libs/cm256cc` should be sufficient. Please try version 1.1.1 and feel free to re-open the issue if there are still problems.

**Comment by CocolinoFan** [comment]
Builds smooth as butter 👍
